### ISSUE TITLE
オンライン対戦機能設計

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/social-resistance#115]
- 現状、フロントエンドで実装している機能のどこまでをバックエンドに持っていけばよいのかの調査

**Comment by tyokinuhata** [comment]
それに伴うカンプの修正まで

**Comment by takashi0602** [comment]
DB

|  word2vec  | 型 | 例 |
| - | - | - |
| word | varchar(255) | "word" |
| move | json | {"x": 1, "y": 1} |

| rooms | 型 | 例 |
| - | - | - |
| room_id | char(6) | 000001 |
| words | json | ["word", "word", ... "word"] |
| turn | int | 1 |
| pekora | json | {name: "name", position: {"x": 1, "y": 1}, word: "word", active: true} |
| baikinKun | json | {name: "name", position: {"x": 1, "y": 1}, word: "word", active: false} |

**Comment by tyokinuhata** [comment]
moveをjson型で持つ必要あるかな？

**Comment by tyokinuhata** [comment]
あとはroomsになんでも詰め込みすぎかと
正規化したほうが良い

**Comment by tyokinuhata** [comment]
個人的にはAPIを先に決めちゃったほうがインタフェースが明確になるんで設計しやすそうなんですがどうなんすかね？
