### ISSUE TITLE
デザインカンプの修正・キャラクターセレクト実装後のデザインカンプの作成

### ISSUE THREAD

**Issue by takashi0602** [uyupun/social-resistance#121]
- [x] デザインカンプと実装の違いをなくす
- [ ] キャラクターセレクト実装に伴うデザインカンプの作成

**Comment by tyokinuhata** [comment]
上記、プレイヤー名の入力は対応する？というかそもそもプレイヤー名の入力機能いるんだろうか、、、

**Comment by tyokinuhata** [comment]
プレイヤー名とかキャラクターの選択、プレイの度に行わせるんじゃなくてFall Guysみたいに設定として保存できる方式にしたいな

**Comment by tyokinuhata** [comment]
というか、現状、機能的にはミニマルな状態にあると思ってて、オンライン化するならベストなタイミングじゃないかと思ってる。
ここから機能が増えてしまうとオンライン対戦として実装するのがつらくなりそう。

**Comment by tyokinuhata** [comment]
となると一旦、フロントの修正はバグ修正 + リファクタ程度にとどめておいて、オンライン対戦の可能性を探っていくのが良さそう

**Comment by tyokinuhata** [comment]
どこをバックエンドに持っていくのか、バックエンドの実装、技術選定はどうするかみたいなところ
