### ISSUE TITLE
カンプの調整後にスタイルを反映する

### ISSUE THREAD

**Issue by takashi0602** [uyupun/social-resistance#158]
- カンプのサイズを調整する(width, height, margin等)
- カンプの修正に伴い、スタイルに反映する

**Comment by tyokinuhata** [comment]
フロントエンド見たのでレビュー
募集画面
全体的にフォントサイズが大きすぎる気がする(他の画面に比べて)
やめる/はじめるボタンが中央になっていない
やめる/はじめるボタンにリンクが設定されていない
参加画面
上下中央揃えしてほしい(画面下部に下がっているように見える)
やめるボタンがない
募集画面と参加画面でボタンサイズが違う
