### ISSUE TITLE
本番環境でのエラー解決

### ISSUE THREAD

**Issue by takashi0602** [uyupun/social-resistance#183]
以下のようなエラーが本番でのみ確認できる
```
WebSocket connection to 'wss://mitsu.uyupun.tech/socket.io/?EIO=3&transport=websocket&sid=FFUxPUlWSFrtoaleAAAD' failed: Error during WebSocket handshake: Unexpected response code: 400
```

**Comment by takashi0602** [comment]
解決策
WebSocket connection to 'wss://mitsu.uyupun.tech/socket.io/?EIO=3&transport=websocket&sid=FFUxPUlWSFrtoaleAAAD' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by tyokinuhata** [comment]
調査

**Comment by tyokinuhata** [comment]
https://qiita.com/risto24/items/d8c2fcbade582a15ca29

**Comment by tyokinuhata** [comment]
https://github.com/socketio/socket.io/issues/1942

**Comment by tyokinuhata** [comment]
nginxの設定を変える必要がありそう

**Comment by tyokinuhata** [comment]
特にこれ？
なんかUpgradeとConnectionの設定ぽいな
https://github.com/socketio/socket.io/issues/1942#issuecomment-697363104

**Comment by tyokinuhata** [comment]
```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
```

**Comment by tyokinuhata** [comment]
> クライアントがサーバに対してプロトコルを切り替えてほしいという依頼し、その依頼が成功したことを表すために101を含んだHTTPレスポンスが返されます。 もっと具体的に述べます。 101(Switching Protocol)はサーバがUpgradeリクエストヘッダーを含んだリクエストを送ったクライアントによって依頼されたプロトコルに切り替えたことを示しています。このレスポンスにはサーバはUpgradeレスポンスヘッダーをレスポンスに含んでいます。Upgradeレスポンスヘッダーはサーバが切り替えたプロトコルを示すために使われます。RFC6455から引用したリクエストとレスポンスはこちらです。

**Comment by tyokinuhata** [comment]
https://www.it-swarm-ja.tech/ja/node.js/websocket%E3%83%8F%E3%83%B3%E3%83%89%E3%82%B7%E3%82%A7%E3%82%A4%E3%82%AF%E4%B8%AD%E3%81%AE%E3%80%8Cwss%EF%BC%9A%E3%80%8D%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%B8%E3%81%AEwebsocket%E6%8E%A5%E7%B6%9A%EF%BC%9A%E4%BA%88%E6%9C%9F%E3%81%97%E3%81%AA%E3%81%84%E5%BF%9C%E7%AD%94%E3%82%B3%E3%83%BC%E3%83%89%EF%BC%9A400/837366966/

**Comment by tyokinuhata** [comment]
`conf.d/mitsu.conf`、 `conf.d/social-resistance.conf` の `proxy_pass` がhttpなのが問題なのではないかと思った

**Comment by tyokinuhata** [comment]
ローカルでの通信でhttps使えるようにしないといけないっぽい？

**Comment by tyokinuhata** [comment]
nginx wss
http://uorat.hatenablog.com/entry/2016/09/19/203939

**Comment by tyokinuhata** [comment]
https://qiita.com/tomi_linka/items/718e12443fd3715519cf
