### ISSUE TITLE
モック作成

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/social-resistance#196]

**Comment by tyokinuhata** [comment]
画面単位での役割分担、たかしのレビュー必須、こまめに

**Comment by takashi0602** [comment]
モックの作成画面
- [ ] /
- [ ] /login
- [ ] /register
- [ ] /join
- [ ] /join/private
- [ ] /join/public
- [ ] /profile/:id
- [ ] /profile/edit
- [ ] /rank
- [ ] /ranking
- [ ] /character-select
- [ ] /rule
