### ISSUE TITLE
ミドルウェアの作成

### ISSUE THREAD

**Issue by takashi0602** [uyupun/social-resistance#215]
- [ ] トークンを保持しているかどうかでリダイレクト処理を行う
- [ ] 無効なトークンを保持している場合は、ログイン画面へリダイレクトさせる

※Vuex入れるか検討

**Comment by tyokinuhata** [comment]
とりあえずsessionStorageで実装する方向でいいと思う

**Comment by tyokinuhata** [comment]
実際に認証を実装するときにそこらへんは考えたいかも

**Comment by takashi0602** [comment]
issue #254 で対応するためClose
