### ISSUE TITLE
CSSリファクタリング

### ISSUE THREAD

**Issue by takashi0602** [uyupun/social-resistance#219]
ref #185

**Comment by tyokinuhata** [comment]
ルール画面のページネーションをline-heightでゴリ押しました。汚いです。すいません。

**Comment by tyokinuhata** [comment]
containerを共通で設定する

**Comment by tyokinuhata** [comment]
https://github.com/uyupun/social-resistance/pull/220#pullrequestreview-521244512

**Comment by tyokinuhata** [comment]
命名規則とかもこれを機にしっかりしたい

**Comment by tyokinuhata** [comment]
フォントサイズをできる限り変数にする

**Comment by tyokinuhata** [comment]
https://kuroeveryday.blogspot.com/2016/10/vue-loader-file-split.html

**Comment by tyokinuhata** [comment]
```
 WARN  Two component files resolving to the same name text-box:

 - /Users/k-tobita/Desktop/index/workspace/social-resistance/components/text-box/index.vue
 - /Users/k-tobita/Desktop/index/workspace/social-resistance/components/text-box/index.js
```

**Comment by tyokinuhata** [comment]
- [ ] containerを共通で設定する
- [ ] 命名規則とかもこれを機にしっかりしたい
- [ ] フォントサイズをできる限り変数にする
- [ ] https://github.com/uyupun/social-resistance/pull/220#pullrequestreview-521244512 これも対応
- [ ] ルール画面のページネーションをline-heightでゴリ押しました。汚いです。すいません
- [ ] RadioButtonGroupを作る
