### ISSUE TITLE
画面サイズが小さい場合のgohomeへ遷移するときの処理

### ISSUE THREAD

**Issue by takashi0602** [uyupun/social-resistance#281]
一定以下の画面幅の時に、募集ページ / 参加ページ(publicとprivate両方)に警告を表示する
BootstrapのAlertみたいな感じで上に表示させる

**Comment by tyokinuhata** [comment]
画面幅が小さくても一応プレイ自体はできるようにしたいから、gohomeでモーダル出すよりもゲームを始める画面でプレイ前に警告だけ出したほうが親切なきがする

**Comment by tyokinuhata** [comment]
@takashi0602 がゲーム画面もうっかりスマホ対応しちゃったのでクローズします
