### ISSUE TITLE
認証の実装

### ISSUE THREAD

**Issue by takashi0602** [uyupun/social-resistance#293]
- [x] ミドルウェアの実装
- [x] APIの送信にtoken載せる
- [x] ログインAPIの繋ぎ込み
- [x] 新規登録APIの繋ぎ込み
- [x] ログアウトの実装

**Comment by tyokinuhata** [comment]
Authorization: Bearerに載せてほしい。WebSocketの場合は要相談かも

**Comment by tyokinuhata** [comment]
JWT認証なのでログアウトはクライアント側からトークンを捨てるという方針で

**Comment by tyokinuhata** [comment]
WebSocket周りはpayloadに載せてる
